language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
sudo: false
cache:
    directories:
        - $TRAVIS_BUILD_DIR/.tox
env:
    - TOXENV=django18
    - TOXENV=django19
matrix:
    exclude:
        - python: "3.3"
          env: TOXENV=django19
install:
    - pip install pyflakes tox
script:
    - pyflakes setup.py runtests.py tests callisto
    - tox
before_cache:
    - rm -r $TRAVIS_BUILD_DIR/.tox/log $TRAVIS_BUILD_DIR/.tox/dist $TRAVIS_BUILD_DIR/.tox/*/log $TRAVIS_BUILD_DIR/.tox/*/lib/python*/site-packages/callisto*
