language: python
python:
    - "3.4"
sudo: false
services:
    - postgresql
install:
    - pip install -r requirements-test.txt
    - pip install pyflakes
script:
    - pyflakes runtests.py delivery evaluation
    - python runtests.py
