language: python
python:
    - "3.4"
sudo: false
cache:
    directories:
        - $HOME/.tox
services:
    - postgresql
env:
    - db_user=postgres
install:
    - pip install pyflakes
script:
    - pyflakes setup.py runtests.py tests callisto
    - tox -e py34-django18,py34-django19
before_cache:
    - rm -r $HOME/.tox/log $HOME/.tox/dist $HOME/.tox/*/log
