language: python
python:
    - "3.4"
sudo: false
services:
    - postgresql
env:
    - db_user=postgres
install:
    - pip install pyflakes
script:
    - pyflakes setup.py runtests.py tests callisto
    - tox -e py34-django18,py34-django19
